#!/usr/bin/env python3
"""Generate siteregister.cpp from a list of site source files.

Convention: site/foo.cpp must define
    namespace pvxs { namespace ioc { namespace site {
    void registerFoo();   // first letter of basename capitalised
    }}}

Usage: gen_siteregister.py site/alarmmsg.cpp site/qdisable.cpp ...
"""

import os
import sys


def registrar_name(path):
    base = os.path.splitext(os.path.basename(path))[0]
    return 'register' + base[0].upper() + base[1:]


def _has_registrar(path, name):
    with open(path) as f:
        return name in f.read()


def generate(srcs):
    names = [registrar_name(s) for s in srcs
             if _has_registrar(s, registrar_name(s))]
    lines = [
        '// Auto-generated by site/gen_siteregister.py -- do not edit.',
        '',
        '#include "sitehooks.h"',
        '',
        'namespace pvxs { namespace ioc { namespace site {',
        '',
    ]
    for name in names:
        lines.append('void {}();'.format(name))
    lines += [
        '',
        'void registerSiteExtensions()',
        '{',
    ]
    for name in names:
        lines.append('    {}();'.format(name))
    lines += [
        '}',
        '',
        '}}} // pvxs::ioc::site',
    ]
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    sys.stdout.write(generate(sys.argv[1:]))
