# This is a Makefile fragment, see cert/authn/Makefile.

SRC_DIRS += $(AUTHN)/ldap

PROD += authnldap
authnldap_INC += authnldap.h
authnldap_INC += configldap.h

authnldap_SRCS += authnldap.cpp
authnldap_SRCS += authnldapmain.cpp
authnldap_SRCS += configldap.cpp
authnldap_SRCS += certstatusfactory.cpp
authnldap_SRCS += certstatus.cpp

pvacms_SRCS += authnldap.cpp
pvacms_SRCS += configldap.cpp
