# This is a Makefile fragment, see cert/authn/Makefile.

SRC_DIRS += $(AUTHN)/jwt

PROD += authnjwt
authnjwt_INC += authnjwt.h
authnjwt_INC += configjwt.h

authnjwt_SRCS += authnjwt.cpp
authnjwt_SRCS += authnjwtmain.cpp
authnjwt_SRCS += configjwt.cpp
authnjwt_SRCS += certstatusfactory.cpp
authnjwt_SRCS += certstatus.cpp

pvacms_SRCS += authnjwt.cpp
pvacms_SRCS += configjwt.cpp
