# This is a Makefile fragment, see cert/authn/Makefile.

SRC_DIRS += $(AUTHN)/std

PROD += authnstd
authnstd_SRCS += authnstd.cpp
authnstd_SRCS += authnstdmain.cpp
authnstd_SRCS += configstd.cpp
authnstd_SRCS += certstatusfactory.cpp
authnstd_SRCS += certstatus.cpp

pvacms_SRCS += authnstd.cpp
pvacms_SRCS += configstd.cpp
