# This is a Makefile fragment, see cert/authn/Makefile.

SRC_DIRS += $(AUTHN)/std

PROD += authnstd
authnstd_INC += authnstd.h
authnstd_INC += configstd.h

authnstd_SRCS += authnstd.cpp
authnstd_SRCS += configstd.cpp
