# This is a Makefile fragment, see src/security/Makefile.

SRC_DIRS += $(TOP)/src/security/authkrb

INC += authkrb.h

LIB_SRCS += authkrb.cpp

KRB_SYS_LIBS = krb5 krb5support com_err
LIB_SYS_LIBS += $(KRB_SYS_LIBS)
