name: Docker Multi-Platform Build Pipeline

on:
  workflow_dispatch:
    inputs:
      build_target:
        description: 'Which image to build'
        required: true
        type: choice
        options:
          - epics-base
          - pvxs
          - spva_std
          - spva_krb
          - spva_ldap
          - all

jobs:
  build-epics-base:
    if: |
      github.event.inputs.build_target == 'epics-base' ||
      github.event.inputs.build_target == 'all'
    uses: george-mcintyre/epics-base/.github/workflows/docker-pub-epics-base.yml@7.0_method_and_authority
    secrets:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  build-pvxs:
    needs: [build-epics-base]
    runs-on: ubuntu-latest
    if: |
      github.event.inputs.build_target == 'pvxs' || 
      github.event.inputs.build_target == 'all' ||
      (needs.build-epics-base.result == 'success')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: tls
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push pvxs
        uses: docker/build-push-action@v5
        with:
          context: example/docker/pvxs/.
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            DOCKER_USERNAME=${{ vars.DOCKER_USERNAME }}
          tags: ${{ vars.DOCKER_USERNAME }}/pvxs:latest

  build-spva-std:
    needs: [build-pvxs]
    runs-on: ubuntu-latest
    if: |
      github.event.inputs.build_target == 'spva_std' || 
      github.event.inputs.build_target == 'all' ||
      (needs.build-pvxs.result == 'success')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: tls
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push spva_std
        uses: docker/build-push-action@v5
        with:
          context: example/docker/spva_std/.
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            DOCKER_USERNAME=${{ vars.DOCKER_USERNAME }}
          tags: ${{ vars.DOCKER_USERNAME }}/spva_std:latest

  build-spva-krb:
    needs: [build-spva-std]
    runs-on: ubuntu-latest
    if: |
      github.event.inputs.build_target == 'spva_krb' ||
      github.event.inputs.build_target == 'all' ||
      (needs.build-spva-std.result == 'success' && github.event.inputs.build_target != 'spva_ldap')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: tls
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push spva_krb
        uses: docker/build-push-action@v5
        with:
          context: example/docker/spva_krb/.
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            DOCKER_USERNAME=${{ vars.DOCKER_USERNAME }}
          tags: ${{ vars.DOCKER_USERNAME }}/spva_krb:latest

  build-spva-ldap:
    needs: [build-spva-std]
    runs-on: ubuntu-latest
    if: |
      github.event.inputs.build_target == 'spva_ldap' || 
      github.event.inputs.build_target == 'all' ||
      (needs.build-spva-std.result == 'success' && github.event.inputs.build_target != 'spva_krb')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: tls
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push spva_ldap
        uses: docker/build-push-action@v5
        with:
          context: example/docker/spva_ldap/.
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            DOCKER_USERNAME=${{ vars.DOCKER_USERNAME }}
          tags: ${{ vars.DOCKER_USERNAME }}/spva_ldap:latest
