name: GH pages

on: [push, pull_request, workflow_dispatch]

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      SETUP_PATH: .ci-local
      SET: defaults
      CMP: gcc
      BCFG: default
      BASE: "7.0"
      _PVXS_ABORT_ON_CRIT: 1
      PVXS_LOG: pvxs.*=WARN

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      with:
        fetch-depth: "0"
        submodules: true

    - name: "apt-get install"
      run: |
        sudo apt-get update
        sudo apt-get -y install \
         doxygen \
         inkscape \
         libevent-dev \
         libreadline-dev \
         python3-breathe \
         python3-sphinx

    - name: Prepare and compile dependencies
      run: python .ci/cue.py prepare

    - name: headers
      run: python .ci/cue.py build inc

    - name: sphinx
      run: |
        make -C documentation gen
        touch documentation/html/.nojekyll

    - name: Upload gh-pages preview
      id: ghpages
      uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4.0.0
      with:
        retention-days: 7
        path: documentation/html/


  publish:
    runs-on: ubuntu-latest

    if: github.ref=='refs/heads/tls'
    needs: generate

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.ghpages.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4
